FROM denvazh/gatling:2.2.2
ADD 0/scala-library-2.11.8.jar 1/nats-connector-gatling_2.11-0.3.0-SNAPSHOT.jar 2/java-nats-streaming-0.1.2.jar 3/jnats-0.5.3.jar 4/slf4j-api-1.7.21.jar 5/protobuf-java-3.0.0.jar 6/guava-19.0.jar ./lib/
ADD 7/user-files ./user-files