FROM denvazh/gatling:3.0.3
ADD 0/scala-library-2.12.8.jar 1/nats-connector-gatling_2.12-1.0.0-SNAPSHOT.jar 2/java-nats-streaming-2.1.2.jar 3/protobuf-java-3.7.0.jar 4/jnats-2.1.0.jar ./lib/
ADD 5/user-files ./user-files