// Jenkinsfile for Inject
// @See https://akomljen.com/set-up-a-jenkins-ci-cd-pipeline-with-kubernetes/

def label = "jenkins-pod3"
podTemplate(label: label, cloud: "openshift", containers: [
  containerTemplate(name: 'sbt', image: 'dsanchor/openshift-jenkins-slave-sbt', command: 'cat', ttyEnabled: true)
]) {
  node(label) {
    stage('Build') {
      container('sbt') {
        sh "sbt version"
      }
    }
  }
}
