version: '2'

services:
  gatling: 
    image: lmagnin/docker-nats-connector-spark:gatling
      
  nats:
    image: nats
    #image: local-docker-cassandra
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
      
  app: 
    image: lmagnin/docker-nats-connector-spark:app
    command: "TestingSubject"
