version: '2'

services:

  nats-main: 
    extends:
      file: common-services.yml
      service: nats
      
  gatling:
    extends:
      file: common-services.yml
      service: gatling
    links: 
      - nats-main
    environment:
      - NATS_URI=nats://nats-main:4222
      
  app:
    extends:
      file: common-services.yml
      service: app
    links: 
      - nats-main
    environment:
      - NATS_URI=nats://nats-main:4222
      - SPARK_MASTER_URL=local[2]
      
  monitor:
    extends:
      file: common-services.yml
      service: monitor
    links: 
      - nats-main
