kind: Template
apiVersion: v1
template: nats-connector
metadata:
  name: nats-connector
labels:
  app: natsconnector
objects:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: inject
  spec:
    replicas: ${INJECT_REPLICAS}
    selector:
      name: inject
    template:
      metadata:
        labels:
          name: inject
      spec:
        containers:
          - name: inject
            image: nats-connector-inject:latest
            imagePullPolicy: Always
            args:
              - '--no-reports'
              - '-s'
              - 'com.logimethods.nats.demo.NatsInjection'
            env:
              - name: GATLING_TO_NATS_SUBJECT
                value: INPUT
              - name: NATS_URI
                value: ${NATS_URI}
            volumeMounts:
            - name: results
              mountPath: /opt/gatling/results
        volumes:
          - name: results
            emptyDir: {}
    triggers:
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
          - inject
          from:
            kind: ImageStreamTag
            name: nats-connector-inject:latest

parameters:
- name: NATS_URI
  description: master name used as a service name and a selector
  value: nats://nats-streaming-server:4222
  required: true
- name: INJECT_REPLICAS
  description: Number of replicas for the injectors
  value: "1"
  required: true
