kind: Template
apiVersion: v1
template: nats-connector
metadata:
  name: nats-connector
labels:
  app: natsconnector
objects:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: inject
  spec:
    replicas: ${INJECT_REPLICAS}
    selector:
      name: inject
    template:
      metadata:
        labels:
          name: inject
      spec:
        containers:
          - name: stats
            image: mribeiro/cloc
            args: ['/git']
            volumeMounts:
            - name: user-files
              mountPath: /git
          - name: inject
            image: ${INJECT_IMAGE}
            args:
              - '--no-reports'
              - '-s'
              - 'com.logimethods.nats.demo.NatsInjection'
            env:
              - name: GATLING_TO_NATS_SUBJECT
                value: INPUT
              - name: NATS_URI
                value: ${NATS_URI}
            volumeMounts:
              - name: user-files
                mountPath: /opt/gatling/user-files
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "while true; do sleep 30; done;" ]
        # These containers are run during pod initialization
        initContainers:
          ## See https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/
          ## See https://blog.schlomo.schapiro.org/2017/06/using-kubernetes-with-multiple.html
          ## See https://github.com/emblica/git-cloner/blob/master/k8s/example.yml
          ## See https://blog.jessfraz.com/post/building-container-images-securely-on-kubernetes/
          - name: install-user-files
            image: emblica/git-cloner
            command: [ "/bin/sh", "-c", "git clone --single-branch -- https://github.com/Logimethods/docker-nats-connector-spark /mnt/git/ ; mv /mnt/git/inject/user-files /mnt/git/user-files"]
            volumeMounts:
            - name: user-files
              mountPath: /mnt/git
        volumes:
          - name: user-files
            emptyDir: {}
#            configMap:
#              name: inject-user-files
#            mountPath: /opt/gatling/user-files

parameters:
- name: INJECT_IMAGE
  description: Inject Docker Image
  value: docker-registry.default.svc:5000/test-build2/nats-connector-inject:latest
  required: true
- name: NATS_URI
  description: master name used as a service name and a selector
  value: nats://nats-streaming-server:4222
  required: true
- name: INJECT_REPLICAS
  description: Number of replicas for the injectors
  value: "1"
  required: true
